import { Product } from '@/types';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'A2 Gir Cow Ghee',
    vol: '2.5L Dolchi',
    price: 5684,
    mrp: 5800,
    off: '2%',
    rat: 4.9,
    revs: '1.2k',
    coins: 284,
    sold: '2,341',
    cat: 'ghee',
    stock: 7,
    badges: ['⭐ TOP RATED', 'BILONA METHOD'],
    pi: 0,
    vars: [{s:'500ml',p:1250},{s:'1L',p:2400},{s:'2.5L',p:5684,on:true},{s:'5L',p:10913}],
    description: 'Made in the farms of Gujarat using the ancient Bilona method — churned from curd, not cream. Rich in A2 beta-casein protein, CLA, and Omega-3 fatty acids.'
  },
  {
    id: 7,
    name: 'Homemade Mango Pickle',
    vol: '500g Glass Jar',
    price: 450,
    mrp: 550,
    off: '18%',
    rat: 4.9,
    revs: '420',
    coins: 25,
    sold: '850',
    cat: 'pickles',
    stock: 15,
    badges: ['🔥 BESTSELLER', 'SUN-DRIED'],
    pi: 1,
    vars: [{s:'250g',p:250},{s:'500g',p:450,on:true},{s:'1kg',p:850}],
    description: 'Traditional Gujarati mango pickle made with sun-dried raw mangoes and cold-pressed mustard oil. No artificial preservatives.'
  },
  {
    id: 8,
    name: 'Raw Forest Honey',
    vol: '500g Glass Jar',
    price: 850,
    mrp: 990,
    off: '14%',
    rat: 4.8,
    revs: '310',
    coins: 40,
    sold: '620',
    cat: 'honey',
    stock: 12,
    badges: ['🍯 UNFILTERED', 'PURE'],
    pi: 2,
    vars: [{s:'250g',p:450},{s:'500g',p:850,on:true}],
    description: 'Pure, raw, and unfiltered honey sourced directly from the forests. Retains all natural pollen and enzymes.'
  },
  {
    id: 9,
    name: 'Artisanal Kaju Katli',
    vol: '500g Box',
    price: 950,
    mrp: 1100,
    off: '13%',
    rat: 5.0,
    revs: '150',
    coins: 50,
    sold: '430',
    cat: 'sweets',
    stock: 8,
    badges: ['🎁 FESTIVE', 'FRESH'],
    pi: 3,
    vars: [{s:'250g',p:500},{s:'500g',p:950,on:true},{s:'1kg',p:1800}],
    description: 'Freshly made Kaju Katli using premium cashews and minimal sugar. A melt-in-the-mouth traditional Indian sweet.'
  },
  {
    id: 2,
    name: 'Desi & Gir Combo',
    vol: '500ml × 2 Jars',
    price: 1850,
    mrp: 2295,
    off: '19%',
    rat: 5.0,
    revs: '892',
    coins: 92,
    sold: '1,108',
    cat: 'combo',
    stock: 13,
    badges: ['19% OFF', '🎁 COMBO'],
    pi: 1,
    vars: [{s:'500ml×2',p:1850,on:true},{s:'1L×2',p:3600}],
    description: 'The ultimate purity package. Includes our signature A2 Gir Cow Ghee and traditional Desi Cow Ghee.'
  },
  {
    id: 10,
    name: 'Stuffed Red Chilli Pickle',
    vol: '400g Glass Jar',
    price: 399,
    mrp: 499,
    off: '20%',
    rat: 4.7,
    revs: '215',
    coins: 20,
    sold: '510',
    cat: 'pickles',
    stock: 9,
    badges: ['🌶️ SPICY'],
    pi: 4,
    vars: [{s:'400g',p:399,on:true}],
    description: 'Hand-stuffed red chillies with a blend of secret ancestral spices and mustard oil.'
  },
  {
    id: 5,
    name: 'Cold Pressed Coconut Oil',
    vol: '1L Glass Bottle',
    price: 699,
    mrp: 850,
    off: '18%',
    rat: 4.6,
    revs: '340',
    coins: 34,
    sold: '560',
    cat: 'oil',
    stock: 18,
    badges: ['🆕 NEW', 'WOOD-PRESSED'],
    pi: 4,
    vars: [{s:'500ml',p:399},{s:'1L',p:699,on:true}],
    description: 'Cold pressed from the finest coastal coconuts. Unrefined and nutrient-rich, ideal for both cooking and personal care.'
  },
  {
    id: 11,
    name: 'Besan Ladoo (Desi Ghee)',
    vol: '500g Box',
    price: 750,
    mrp: 850,
    off: '12%',
    rat: 4.9,
    revs: '180',
    coins: 35,
    sold: '390',
    cat: 'sweets',
    stock: 11,
    badges: ['🔥 POPULAR'],
    pi: 5,
    vars: [{s:'250g',p:400},{s:'500g',p:750,on:true}],
    description: 'Slow-roasted besan (gram flour) in pure Desi Ghee, finished with crunchy nuts and cardamom.'
  }
];

export const TESTIMONIALS = [
  {
    name: 'Priya Sharma',
    loc: 'Mumbai · Verified Buyer',
    time: '3 months ago',
    body: '"The aroma of the ghee fills the entire kitchen. And the mango pickle takes me back to my grandmother\'s house. Pure nostalgia!"',
    prod: 'A2 Gir Cow Ghee & Mango Pickle',
    avatar: '👩'
  },
  {
    name: 'Rajan Kulkarni',
    loc: 'Hyderabad · Verified Buyer',
    time: '1 month ago',
    body: '"The Kaju Katli was so fresh and not overly sweet. It\'s hard to find such artisanal quality online. Highly recommended!"',
    prod: 'Artisanal Kaju Katli',
    avatar: '🧔'
  },
  {
    name: 'Meena Joshi',
    loc: 'Pune · Verified Buyer',
    time: '2 weeks ago',
    body: '"I use the forest honey every morning. It\'s clear, thick, and tastes like real honey should. Vivaan Farms is now my go-to for all farm goods."',
    prod: 'Raw Forest Honey',
    avatar: '🧕'
  }
];

export const CERTS = [
  { abbr: 'ISO 9001', color: '#1A5C38' },
  { abbr: 'ISO 22000', color: '#1A5C38' },
  { abbr: 'FSSAI', color: '#2A6A48' },
  { abbr: 'FDA', color: '#0A3A1A' },
  { abbr: 'GMP CERTIFIED', color: '#1A5C38' },
  { abbr: 'NABL', color: '#2A5A3A' },
  { abbr: 'HACCP', color: '#1A5C38' },
];
